apiVersion: extensions.triggermesh.io/v1alpha1
kind: KnativeSourceRegistration
metadata:
  name: dataweavetransformation
spec:

  generate:
    names:
      kind: DataweaveTransformation
      plural: dataweavetransformations

  workload:
    fromImage:
      repo: gcr.io/triggermesh/dw:latest
    formFactor:
      knativeService:
        minScale: 1
        maxScale: 10

    parameterOptions:
      arbitraryParameters: false
      keyCasing: upper

  configuration:
    parameters:
    - name: dw_spell
      type: string
    - name: output_content_type
      type: string
    - name: incoming_content_type
      type: string
