# Copyright 2022 TriggerMesh Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: sources.knative.dev/v1
kind: PingSource
metadata:
    name: cj
spec:
    data: |-
        {
            "books": [
              {
                "-category": "cooking",
                "title":"Everyday Italian",
                "author": "Giada De Laurentiis",
                "year": "2005",
                "price": "30.00"
              },
              {
                "-category": "children",
                "title": "Harry Potter",
                "author": "J K. Rowling",
                "year": "2005",
                "price": "29.99"
              },
              {
                "-category": "web",
                "title":  "XQuery Kick Start",
                "author": [
                  "James McGovern",
                  "Per Bothner",
                  "Kurt Cagle",
                  "James Linn",
                  "Vaidyanathan Nagarajan"
                ],
                "year": "2003",
                "price": "49.99"
              },
              {
                "-category": "web",
                "-cover": "paperback",
                "title": "Learning XML",
                "author": "Erik T. Ray",
                "year": "2003",
                "price": "39.95"
              }
            ]
        }
    schedule: '*/1 * * * *'
    sink:
      ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: dataweavetransformations-hello-dw
