apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-world
spec:
  template:
    spec:
      containers:
        - image: amansarraf/test
          env:
          - name: PORT
            value: 8080