apiVersion: flow.triggermesh.io/v1alpha1
kind: Transformation
metadata:
  name: aquasec-transformation
spec:
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: sockeye
  data:
  - operation: parse
    paths:
    - key: Body
      value: JSON
  - operation: store
    paths:
    - key: $control
      value: Body.data.control
    - key: $id
      value: Body.data.id
    - key: $hostid
      value: Body.data.hostid
    - key: $reason
      value: Body.data.reason
    - key: $time
      value: Body.data.time
    - key: $containerid
      value: Body.data.containerid
    - key: $category
      value: Body.data.category
    - key: $container
      value: Body.data.container
    - key: $region
      value: Body.data.vm_location
    - key: $image
      value: Body.data.image
    - key: $name
      value: Body.data.container
    - key: $guid
      value: Body.data.containerid
    - key: $tatic
      value: Body.data.tatic

  - operation: delete
    paths:
    - key:

  - operation: add
    paths:
    - key: provider
      value: Aquasec
    - key: providerType
      value: aquasec
    - key: providerId
      value: $id
    - key: source.sourceName
      value: Aquasec
    - key: source.sourceId
      value: none
    - key: provider.accountId
      value: $id
    - key: event.guid
      value: $guid
    - key: event.name
      value: $name
    - key: event.shortDescription
      value: "an aquasec short description goes here"
    - key: event.startTime
      value: $time
    - key: event.severity
      value: HIGH
    - key: event.status
      value: OPEN
    - key: resource.identifier
      value: $id
    - key: resource.type
      value: $tatic
    - key: resource.name
      value: $hostid
    - key: resource.region
      value: us-1-c
    - key: resource.zone
      value: us
