apiVersion: extensions.triggermesh.io/v1alpha1
kind: KnativeSourceRegistration
metadata:
  name: javascriptadapter
spec:

  generate:
    names:
      kind: JavascriptAdapter
      plural: javascriptadapter

  workload:
    fromImage:
      repo: gcr.io/ultra-hologram-297914/js:latest
    formFactor:
      knativeService:
        minScale: 1
        maxScale: 10

    parameterOptions:
      arbitraryParameters: false
      keyCasing: upper

  configuration:
    parameters:
    - name: query
      type: string
