# This is to enforce good golang linting practice

name: lint

# Controls when the workflow will run
on:

  push:
    branches:
    - master
    - develop
    - release-*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:

    - name: checkout
      uses: actions/checkout@v2

    - name: run linter
      uses: golangci/golangci-lint-action@v2
