# This workflow is ensure that the projects build and lint correctly.

name: lintandbuild

# Controls when the workflow will run
on:

  push:
    branches:
    - master
    - develop

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: checkout
      uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: '^1.17.0'

    - name: Install golangci-lint
      run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.18.0

    - name: run linter
      run: make lint

    - name: build adapters
      run: make build
